import maya.cmds as cmds

cmds.select()
listSel = cmds.ls(sl=True)
for n in listSel:

	cmds.deleteAttr( n + '.rsAOCaster' )
	cmds.deleteAttr( n + '.rsAutoBumpMap' )
	cmds.deleteAttr( n + '.rsCausticCaster' )
	cmds.deleteAttr( n + '.rsCausticReceiver' )
	cmds.deleteAttr( n + '.rsCausticVisible' )
	cmds.deleteAttr( n + '.rsDisplacementScale' )
	cmds.deleteAttr( n + '.rsDoSmoothSubdivision' )
	cmds.deleteAttr( n + '.rsEnableDisplacement' )
	cmds.deleteAttr( n + '.rsEnableSubdivision' )
	cmds.deleteAttr( n + '.rsEnableVisibilityOverrides' )
	cmds.deleteAttr( n + '.rsFgCaster' )
	cmds.deleteAttr( n + '.rsFgVisible' )
	cmds.deleteAttr( n + '.rsForceBruteForceGI' )
	cmds.deleteAttr( n + '.rsGiCaster' )
	cmds.deleteAttr( n + '.rsGiReceiver' )
	cmds.deleteAttr( n + '.rsGiVisible' )
	cmds.deleteAttr( n + '.rsMatteAffectedByMatteLights' )
	cmds.deleteAttr( n + '.rsMatteAlpha' )
	cmds.deleteAttr( n + '.rsMatteApplyToSecondaryRays' )
	cmds.deleteAttr( n + '.rsMatteDiffuseScale' )
	cmds.deleteAttr( n + '.rsMatteEnable' )
	cmds.deleteAttr( n + '.rsMatteReflectionScale' )
	cmds.deleteAttr( n + '.rsMatteRefractionScale' )
	cmds.deleteAttr( n + '.rsMatteShadowAffectsAlpha' )
	cmds.deleteAttr( n + '.rsMatteShadowTransparency' )
	cmds.deleteAttr( n + '.rsMatteShowBackground' )
	cmds.deleteAttr( n + '.rsMaxDisplacement' )
	cmds.deleteAttr( n + '.rsMaxTessellationSubdivs' )
	cmds.deleteAttr( n + '.rsMinTessellationLength' )
	cmds.deleteAttr( n + '.rsObjectId' )
	cmds.deleteAttr( n + '.rsOutOfFrustumTessellationFactor' )
	cmds.deleteAttr( n + '.rsPrimaryRayVisible' )
	cmds.deleteAttr( n + '.rsReflectionCaster' )
	cmds.deleteAttr( n + '.rsReflectionVisible' )
	cmds.deleteAttr( n + '.rsRefractionCaster' )
	cmds.deleteAttr( n + '.rsRefractionVisible' )
	cmds.deleteAttr( n + '.rsScreenSpaceAdaptive' )
	cmds.deleteAttr( n + '.rsSecondaryRayVisible' )
	cmds.deleteAttr( n + '.rsSelfShadows' )
	cmds.deleteAttr( n + '.rsShadowCaster' )
	cmds.deleteAttr( n + '.rsShadowReceiver' )
	cmds.deleteAttr( n + '.rsSubdivisionRule' )
	cmds.deleteAttr( n + '.rsMatteShadowEnable' )
	cmds.deleteAttr( n + '.rsMatteShadowColor' )
